<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <?php if (!empty($list)) { ?>
        <h3><?php _e('List of categories'); ?></h3>
        <table class="table table-striped table-bordered table-sm">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Slug'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $category) { ?>
                <?php if ($category['status'] == 1) {
                    $badgeIdClass = 'badge-success';
                } elseif ($category['status'] == 5) {
                    $badgeIdClass = 'badge-danger';
                } else {
                    $badgeIdClass = 'badge-warning';
                } ?>
                <tr>
                    <td>
                        <span class="badge <?php echo $badgeIdClass; ?>"><?php echo $this->escape($category['id']); ?></span>
                    </td>
                    <td><?php echo $this->escape($category['title']); ?></td>
                    <td><?php echo $this->escape($category['slug']); ?></td>
                    <td>
                        <a target="_blank" class="btn btn-success btn-sm" title="<?php _e('View'); ?>"
                           href="<?php echo $this->url('api', ['controller' => 'custom', 'action' => 'index', 'slug' => $category['slug']]); ?>">
                            <i class="fa fa-eye"></i> <?php _e('View'); ?>
                        </a>

                        <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', ['action' => 'categoryUpdate', 'id' => $category['id']]); ?>">
                            <i class="fa fa-edit"></i> <?php _e('Edit'); ?>
                        </a>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php echo _a('You dont have any category yet, please generate new one'); ?>
        </div>
    <?php } ?>
</div>