<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <?php if (!empty($list)) { ?>
        <h3><?php _e('List of items'); ?></h3>
        <table class="table table-striped table-bordered table-sm">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Category'); ?></th>
                <th><?php _e('Key'); ?></th>
                <th><?php _e('Value'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $item) { ?>
                <?php if ($item['status'] == 1) {
                    $badgeIdClass = 'badge-success';
                } elseif ($item['status'] == 5) {
                    $badgeIdClass = 'badge-danger';
                } else {
                    $badgeIdClass = 'badge-warning';
                } ?>
                <tr>
                    <td>
                        <span class="badge <?php echo $badgeIdClass; ?>"><?php echo $this->escape($item['id']); ?></span>
                    </td>
                    <td><?php echo $this->escape($item['title']); ?></td>
                    <td><?php echo $this->escape($item['category']); ?></td>
                    <td><?php echo $this->escape($item['key']); ?></td>
                    <td><?php echo $this->escape($item['value']); ?></td>
                    <td>
                        <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', ['action' => 'itemUpdate', 'id' => $item['id']]); ?>">
                            <i class="fa fa-edit"></i> <?php _e('Edit'); ?>
                        </a>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php echo _a('You dont have any item yet, please generate new one'); ?>
        </div>
    <?php } ?>
</div>