<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <?php if (!empty($list)) { ?>
        <h3><?php _e('List of social networks'); ?></h3>
        <table class="table table-striped table-bordered table-sm">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Slug'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $social) { ?>
                <?php if ($social['status'] == 1) {
                    $labelIdClass = 'label-success';
                } elseif ($social['status'] == 5) {
                    $labelIdClass = 'label-danger';
                } else {
                    $labelIdClass = 'label-warning';
                } ?>
                <tr>
                    <td>
                        <span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($social['id']); ?></span>
                    </td>
                    <td>
                        <a target="_blank" href="<?php echo $this->escape($social['url']); ?>"
                           title="<?php echo $this->escape($social['title']); ?>">
                            <i class="fa <?php echo $this->escape($social['icon']); ?>"></i> <?php echo $this->escape($social['title']); ?>
                        </a>
                    </td>
                    <td><?php echo $this->escape($social['slug']); ?></td>
                    <td>
                        <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', ['action' => 'update', 'id' => $social['id']]); ?>"><i
                                    class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <p><?php echo _a('You dont have any social network yet, please add new one'); ?></p>
        </div>
    <?php } ?>
</div>