<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <?php if (!empty($list)) { ?>
        <h3><?php _e('List of tokens'); ?></h3>
        <table class="table table-striped table-bordered table-sm">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Last usd time'); ?></th>
                <th><?php _e('Used'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($list as $token) { ?>
                <?php if ($token['status'] == 1) {
                    $badgeIdClass = 'badge-success';
                } elseif ($token['status'] == 5) {
                    $badgeIdClass = 'badge-danger';
                } else {
                    $badgeIdClass = 'badge-warning';
                } ?>
                <tr>
                    <td>
                        <span class="badge <?php echo $badgeIdClass; ?>"><?php echo $this->escape($token['id']); ?></span>
                    </td>
                    <td><?php echo $this->escape($token['title']); ?></td>
                    <td><?php echo $this->escape($token['time_used_view']); ?></td>
                    <td><?php echo $this->escape($token['used_view']); ?></td>
                    <td>
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-success btn-sm" data-toggle="modal"
                                data-target="#tokenModal<?php echo $this->escape($token['id']); ?>">
                            <?php _e('View token'); ?>
                        </button>
                        <!-- Modal -->
                        <div class="modal fade" id="tokenModal<?php echo $this->escape($token['id']); ?>" tabindex="-1"
                             role="dialog" aria-labelledby="tokenModalLabel<?php echo $this->escape($token['id']); ?>">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal"
                                                aria-label="<?php _e('Close'); ?>"><span
                                                    aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title"
                                            id="tokenModalLabel<?php echo $this->escape($token['id']); ?>"><?php _e('Token information'); ?></h4>
                                    </div>
                                    <div class="modal-body">
                                        <p class="token-view"><?php echo $this->escape($token['token']); ?></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', ['action' => 'update', 'id' => $token['id']]); ?>">
                            <i class="fa fa-edit"></i> <?php _e('Edit'); ?>
                        </a>
                    </td>
                </tr>
            <?php } ?>
        </table>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php echo _a('You dont have any token yet, please generate new one'); ?>
        </div>
    <?php } ?>
</div>