<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="alert alert-info">
        <?php echo $message; ?>
    </div>
    <h1><?php _e('List of users on csv file'); ?></h1>
    <?php foreach ($users as $user) { ?>
        <pre><?php print_r($user); ?></pre>
    <?php } ?>
    <p>
        <a title="<?php _e('Add all users'); ?>" href="<?php echo Pi::url($this->url('', [
            'action'  => 'import',
            'addUser' => 'OK',
        ])); ?>" class="btn btn-primary btn-lg"><?php _e('Add all users'); ?></a>
    </p>
</div>