<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <?php if ($confirm == 0) { ?>
        <div class="clearfix alert alert-success">
            <div class="row">
                <div class="col-md-9">
                    <?php _e(
                        'For make new csv file from website users, please click on below button and wait to generate file possess completed, after that you can download list of users as csv file'
                    ); ?>
                </div>
                <div class="col-md-3 text-right">
                    <a title="<?php _e('Export users'); ?>" href="<?php echo Pi::url(
                        $this->url(
                            '', [
                            'action' => 'export',
                            'confirm' => 1,
                        ]
                        )
                    ); ?>" class="btn btn-success"><i class="fa fa-users"
                                                      aria-hidden="true"></i> <?php _e('Export users'); ?></a>
                </div>
            </div>
        </div>
    <?php } else { ?>
        <div class="progress progress-striped active">
            <div class="progress-bar" role="progressbar" aria-valuenow="<?php echo $percent; ?>" aria-valuemin="0"
                 aria-valuemax="100" style="width: <?php echo $percent; ?>%">
                <?php echo $percent; ?> % Complete
            </div>
        </div>
        <pre><?php print_r($info); ?></pre>
    <?php if (!empty($nextUrl)) { ?>
        <script>
            window.setTimeout(function () {
                window.location.href = '<?php echo $nextUrl; ?>';
            }, 1000);
        </script>
    <?php } elseif ($downloadAllow) { ?>
        <div class="clearfix">
            <ul class="list-group-item list-inline">
                <li class="list-inline-item"><?php echo $file; ?></li>
                <li class="list-inline-item">
                    <a href="<?php echo Pi::url(
                        $this->url(
                            '', [
                            'action' => 'download',
                            'type'   => 'csv',
                            'file'   => $file,
                        ]
                        )
                    ); ?>">
                        <i class="fa fa-cloud-download" aria-hidden="true"></i> <?php _e('CSV version'); ?>
                    </a>
                </li>
            </ul>
        </div>
    <?php } ?>
    <?php } ?>
    <?php if (isset($fileList) && !empty($fileList)) { ?>
        <h3><?php _e('List of old exported files'); ?></h3>
        <div class="list-group">
            <?php arsort($fileList); ?>
            <?php foreach ($fileList as $file) { ?>
                <?php if (substr($file, 0, 11) === 'user-export') { ?>
                    <?php $fileName = pathinfo($file, PATHINFO_FILENAME); ?>
                    <ul class="list-group-item list-inline">
                        <li class="list-inline-item"><?php echo $fileName; ?></li>
                        <li class="list-inline-item">
                            <a href="<?php echo Pi::url(
                                $this->url(
                                    '', [
                                    'action' => 'download',
                                    'type'   => 'csv',
                                    'file'   => $fileName,
                                ]
                                )
                            ); ?>">
                                <i class="fa fa-cloud-download" aria-hidden="true"></i> <?php _e('CSV version'); ?>
                            </a>
                        </li>
                    </ul>
                <?php } ?>
            <?php } ?>
        </div>
    <?php } ?>
</div>