<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="alert alert-success">
        <div class="row">
            <div class="col-md-9">
                <?php _e('Download this example file and put your user information on it upload on server and import user on DB'); ?>
            </div>
            <div class="col-md-3 text-right">
                <a target="_blank" title="<?php _e('Example'); ?>"
                   href="<?php echo $this->assetModule('csv/user-import.csv'); ?>"
                   class="btn btn-success">
                    <i class="fa fa-cloud-download" aria-hidden="true"></i> <?php _e('Example'); ?>
                </a>
            </div>
        </div>
    </div>
    <div class="alert alert-info">
        <?php echo $message; ?>
    </div>
    <?php if (!empty($users)) { ?>
        <h3><?php _e('List of users on csv file'); ?></h3>
        <?php foreach ($users as $user) { ?>
            <pre><?php print_r($user); ?></pre>
        <?php } ?>
        <p>
            <a title="<?php _e('Add all users'); ?>" href="<?php echo Pi::url(
                $this->url(
                    '', [
                    'action'  => 'import',
                    'addUser' => 'OK',
                ]
                )
            ); ?>" class="btn btn-primary btn-lg"><?php _e('Add all users'); ?></a>
        </p>
    <?php } ?>
</div>